"""Boundary update component for WW3 configuration."""

from typing import Optional
from ..namelists.restart import Update
from .basemodel import WW3ComponentBaseModel


class BoundaryUpdateComponent(WW3ComponentBaseModel):
    """Component for ww3_bounc.nml containing boundary update configuration."""

    update: Optional[Update] = None

    def render(self) -> str:
        """Render the boundary update component as a combined namelist string."""
        bounc_content = []
        bounc_content.append("! WW3 boundary update configuration")
        bounc_content.append("! Generated by rompy-ww3")
        bounc_content.append("")

        # Add UPDATE NML if defined (for boundary updates)
        if self.update:
            rendered = self.update.render().replace("\\n", "\n")
            bounc_content.extend(rendered.split("\n"))
            bounc_content.append("")
        else:
            # Default boundary update configuration
            bounc_content.append("&BOUN_UPDATE_NML")
            bounc_content.append("  BOUN_UPDATE%UPDATE_TYPE  = 'FLUX'")
            bounc_content.append("  BOUN_UPDATE%INTERP_TYPE = 'LINEAR'")
            bounc_content.append("/")
            bounc_content.append("")

        return "\n".join(bounc_content)
