"""Field preprocessor component for WW3 configuration."""

from typing import Optional
from pydantic import Field
from ..namelists.forcing import Forcing
from ..namelists.file import File
from .basemodel import WW3ComponentBaseModel


class FieldPreprocessorComponent(WW3ComponentBaseModel):
    """Component for ww3_prnc.nml containing field preprocessing configuration."""

    forcing: Optional[Forcing] = None
    file: Optional[File] = Field(
        default=None, description="FILE_NML configuration for input file preprocessing"
    )

    def render(self) -> str:
        """Render the field preprocessor component as a combined namelist string."""
        prnc_content = []
        prnc_content.append("! WW3 field preprocessor configuration")
        prnc_content.append("! Generated by rompy-ww3")
        prnc_content.append("")

        # Add FORCING NML if defined
        if self.forcing:
            rendered = self.forcing.render().replace("\\n", "\n")
            prnc_content.extend(rendered.split("\n"))
            prnc_content.append("")
        else:
            # Default forcing configuration
            prnc_content.append("&FORCING_NML")
            prnc_content.append("  FORCING%TIDAL = 'FAST'")
            prnc_content.append("/")
            prnc_content.append("")

        # Add FILE NML if defined
        if self.file:
            rendered = self.file.render().replace("\\n", "\n")
            prnc_content.extend(rendered.split("\n"))
        else:
            # Default file configuration
            prnc_content.append("&FILE_NML")
            prnc_content.append(
                "  FILE%FILENAME = 'input.nc'  ! Default input filename"
            )
            prnc_content.append("/")
            prnc_content.append("")

        return "\n".join(prnc_content)
