"""Field output component for WW3 configuration."""

from typing import Optional
from ..namelists.unformatted import UnformattedOutput
from .basemodel import WW3ComponentBaseModel


class FieldOutputComponent(WW3ComponentBaseModel):
    """Component for ww3_ounf.nml containing field (NetCDF) output configuration."""

    unformatted: Optional[UnformattedOutput] = None

    def render(self) -> str:
        """Render the field output component as a combined namelist string."""
        ounf_content = []
        ounf_content.append("! WW3 field output configuration")
        ounf_content.append("! Generated by rompy-ww3")
        ounf_content.append("")

        # Add FIELD OUTPUT NML if defined
        if self.unformatted:
            rendered = self.unformatted.render().replace("\\n", "\n")
            ounf_content.extend(rendered.split("\n"))
            ounf_content.append("")
        else:
            # Default field output configuration
            ounf_content.append("&OUNF_NML")
            ounf_content.append("  OUNF%HSIGN = 'T'")
            ounf_content.append("  OUNF%TMM10 = 'T'")
            ounf_content.append("  OUNF%TM02 = 'T'")
            ounf_content.append("  OUNF%PDIR = 'T'")
            ounf_content.append("  OUNF%PENT = 'T'")
            ounf_content.append("/")
            ounf_content.append("")

        return "\n".join(ounf_content)
