"""Parameters component for WW3 configuration."""

from typing import Optional
from ..namelists.parameters import ModelParameters
from .basemodel import WW3ComponentBaseModel


class ParametersComponent(WW3ComponentBaseModel):
    """Component for namelists.nml containing model parameters configuration."""

    parameters: Optional[ModelParameters] = None

    def render(self) -> str:
        """Render the parameters component as a combined namelist string."""
        params_content = []
        params_content.append("! WW3 model parameters configuration")
        params_content.append("! Generated by rompy-ww3")
        params_content.append("")

        # Add MODEL PARAMETERS NML if defined
        if self.parameters:
            rendered = self.parameters.render().replace("\\n", "\n")
            params_content.extend(rendered.split("\n"))
            params_content.append("")
        else:
            # Default model parameters configuration
            params_content.append("&PARAMS_NML")
            params_content.append("  PARAMS%VISCOSITY = 1.0E-04")
            params_content.append("  PARAMS%DENST_REF = 1025.0")
            params_content.append("  PARAMS%LAPLACIAN = 'T'")
            params_content.append("/")
            params_content.append("")

        return "\n".join(params_content)
