"""Parameters component for WW3 configuration."""

from typing import Optional
from ..namelists.parameters import ModelParameters
from .basemodel import WW3ComponentBaseModel


class ParametersComponent(WW3ComponentBaseModel):
    """Component for namelists.nml containing model parameters configuration."""

    parameters: Optional[ModelParameters] = None

    def render(self) -> str:
        """Render the parameters component as a combined namelist string."""
        params_content = []
        params_content.append("! WW3 model parameters configuration")
        params_content.append("! Generated by rompy-ww3")
        params_content.append("")
