"""Restart update component for WW3 configuration."""

from typing import Optional
from ..namelists.restartupdate import RestartUpdate
from .basemodel import WW3ComponentBaseModel


class RestartUpdateComponent(WW3ComponentBaseModel):
    """Component for ww3_uprstr.nml containing restart update configuration."""

    restart_update: Optional[RestartUpdate] = None

    def render(self) -> str:
        """Render the restart update component as a combined namelist string."""
        uprstr_content = []
        uprstr_content.append("! WW3 restart update configuration")
        uprstr_content.append("! Generated by rompy-ww3")
        uprstr_content.append("")

        # Add RESTART UPDATE NML if defined
        if self.restart_update:
            rendered = self.restart_update.render().replace("\\n", "\n")
            uprstr_content.extend(rendered.split("\n"))
            uprstr_content.append("")
        else:
            # Default restart update configuration
            uprstr_content.append("&UPRSTR_NML")
            uprstr_content.append("  UPRSTR%UPDATE_RESTART = 'T'")
            uprstr_content.append("/")
            uprstr_content.append("")

        return "\n".join(uprstr_content)
