"""Track component for WW3 configuration."""

from typing import Optional
from ..namelists.track import Track
from .basemodel import WW3ComponentBaseModel


class TrackComponent(WW3ComponentBaseModel):
    """Component for ww3_trnc.nml containing track output configuration."""

    track: Optional[Track] = None

    def render(self) -> str:
        """Render the track component as a combined namelist string."""
        trnc_content = []
        trnc_content.append("! WW3 track output configuration")
        trnc_content.append("! Generated by rompy-ww3")
        trnc_content.append("")

        # Add TRACK_NML if defined
        if self.track:
            rendered = self.track.render().replace("\\n", "\n")
            trnc_content.extend(rendered.split("\n"))
            trnc_content.append("")
        else:
            # Default track output configuration
            trnc_content.append("&TRACK_NML")
            trnc_content.append("  TRACK%ACTIVE = 'T'  ! Enable track output")
            trnc_content.append("  TRACK%FORMAT = 1    ! Track format")
            trnc_content.append("/")
            trnc_content.append("")

        return "\n".join(trnc_content)
