#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECKSUM_FILE="$SCRIPT_DIR/CHECKSUMS.txt"

echo "Generating checksums for reference outputs..."
echo ""

cat > "$CHECKSUM_FILE" <<'HEADER'
# SHA256 checksums for WW3 reference outputs
# Generated by update_checksums.sh
#
# Verify with: sha256sum -c CHECKSUMS.txt
# Update with: ./update_checksums.sh

# Format: <sha256>  <filepath>

HEADER

find "$SCRIPT_DIR" -type f \( -name "*.nc" -o -name "*.ww3" -o -name "*.spec" -o -name "*.out" \) \
    -exec sha256sum {} \; | sed "s|$SCRIPT_DIR/||" >> "$CHECKSUM_FILE"

echo "Checksums updated: $CHECKSUM_FILE"
