"""
Test cases for WW3 template context generation.
"""

import tempfile
from pathlib import Path
from rompy_ww3.config import Config
from rompy_ww3.namelists import Domain, Input


def test_template_context_generation():
    """Test template context generation."""

    # Create a config with some components
    config = Config(
        domain=Domain(start="20230101 000000", stop="20230102 000000", iostyp=1),
        input_nml=Input(forcing={"winds": "T", "water_levels": "T"}),
    )

    # Generate template context
    context = config.get_template_context()

    print("Template context keys:")
    for key in context.keys():
        print(f"  - {key}")

    # Check that expected keys are present
    assert "config" in context
    assert "domain" in context
    assert "input_nml" in context
    assert "namelists" in context
    assert "start_time" in context
    assert "stop_time" in context
    assert "forcing" in context

    # Check values
    assert context["start_time"] == "20230101 000000"
    assert context["stop_time"] == "20230102 000000"
    assert context["forcing"]["winds"] == "T"
    assert context["forcing"]["water_levels"] == "T"

    # Check that namelists are rendered
    assert "domain.nml" in context["namelists"]
    assert "input.nml" in context["namelists"]

    print("\nTemplate context generation test passed!")


def test_run_script_generation():
    """Test run script generation."""

    config = Config()

    with tempfile.TemporaryDirectory() as tmpdir:
        workdir = Path(tmpdir) / "run"
        script_path = config.generate_run_script(workdir)

        assert script_path.exists()
        assert script_path.name == "run_ww3.sh"

        # Check that script has expected content
        content = script_path.read_text()
        assert "# WW3 run script generated by rompy-ww3" in content
        assert "ww3_grid" in content
        assert "ww3_shel" in content

        print(f"Generated run script: {script_path}")
        print("\nRun script generation test passed!")


if __name__ == "__main__":
    test_template_context_generation()
    test_run_script_generation()
    print("\nAll template context tests passed!")
